<?php
   $respuestas = array(
       "Es feo cuando no sabes si rompiste, o te rompieron - Perotti Preocupado",
	"No se conforman con nada, bueno me pondré a bailar en zunga - Perotti Coqueto",
	"Cualquier ciego puede ver ese jinete - Perotti Exigente",
	"No te preocupes yo me Auto Mato - Larry Perotti",
	"Se termina terminando - Perotti Redundante",
	"Que mala idea fue meterme esto en la boca - Perotti XXX",
	"Espera, ¿no puse play? ¡Estaba casteando solo, como un boludo! - Perotti Distraído",
	"Caballitos a caballos - Perotti Redundante",
	"Se me tapó el mate, estoy chupando como XVídeos - Perotti XXX",
	"Se me cambió de vaso el lugar - Perotti Ebrio",
	"Se me suicidó, solo, solito y solo - Perotti Redundante",
	"Por ARS50 te puedo mostrar un pezón, tampoco soy tan barato – StriPerotti",
	"Nunca está bueno que te entren de a dos - Perotti Preocupado",
	"Es como una suerte de telepatía animalesca - Perotti Erudito",
	"Donde miro, veo t3t4s - Perotti Mirón",
	"Debe estar transpirando como salam3 adentro de la guantera, una tarde de verano con el rayo del sol en un auto negro - Perotti Filósofo",
	"¡Cómo me duele el Age! Mejor me dedico a la guitarra - Perotti GG",
	"Uno se pone ansioso, como niño con chiche nuevo - Perotti Juguetón",
	"Tengo un patio medio chico, y no me entra - Perotti Chico",
	"O sea no, pero sí... ¡Ustedes entienden! - Perotti Shakesperiano",
	"Aldeana, castéame la comida - Perotti Comelón",
	"Está muriendo porque lo matan - Perotti Redundante",
	"Por cada vez que se me corte, me voy a cortar un huevo",
	"Así que sólo se me puede cortar... 3 veces - Perotti Masoquista",
	"Me estoy cagando de frío, ¡que menopáusico del orto! - Perotti Indeciso",
	"O me pongo en patas, o me corto las uñas de los pies - Perotti Indeciso",
	"¡Juegue al Age, mueva la burra! - Perotti Exigente",
	"¡Vamos! Me chupa un huevo las civilizaciones. ¡Tenemos que ganar, Vamos Argentina! - Perotti Patriota",
	"España la tiene más gorda - Perotti Goloso",
	"Se me atoró una banana en la garganta - Perotti Goloso",
	"Mmmm... Esta salchicha es demasiado grande para comérsela de un solo bocado - Perotti Goloso",
	"¡Ay! se me escapa la salchicha - Perotti Comiendo",
	"No puedo castear mucho con semejante salchicha en la boca - Perotti XXX",
	"Mmmm… Haceme una ligera turca - Perotti Goloso",
	"Casi me como el micrófono, que incómodo esto - Perotti Inexperto",
	"Después de esto, tiras el GG y te vas a dormir llorando - Perotti Ansioso",
	"Cualquier lagrimón diría que es stream cheat - Perotti Erudito",
	"¡Ay no! ¡El hoyo, el hoyo! ¡Te acaban de ingresar por el hoyo! - Perotti Preocupado",
	"¡Pelee! ¡Pelee! No importa que pierda - Perotti Descontrolado",
	"Me voy a comprar un WD40 para los dedos - Perotti Oxidado",
	"Gracias amigos por financiarme el líquido lubricante... para las articulaciones - Perotti Agradecido",
	"¡Ay que dolor!, Esto de ser argentino ya no me gusta - Perotti Traidor",
	"Ustedes me entienden, y si no me entienden no importa - Perotti Indiferente",
	"Ya no entiendo más de Age, que castee otro... - Perotti Shockeado",
	"¡Hay que transpirar Age, estamos transpirando Age! - Perotti Acalorado",
	"¡Qué lindo que es el Age! - Perotti Entusiasmado",
	"¡Ay Tío! Como no haber salido gay para ser marido tuyo - Perotti Confundido",
	"Galletitas Trío... el único trío al que puedo aspirar - Perotti Goloso",
	"No es buena idea tomar vino con unas alemanas - Perotti Conquistador",
	"Estoy imaginando partidas que no suceden - Perotti Delirante",
	"Una pesca para pescar pescado - Perotti Redundante",
	"Acá no estudia nadie porque son burros, dejan la puerta abierta - Perotti Erudito",
	"Todos mis amigos del Flauta están capacitados... menos Diego - Perotti Amigo",
	"A veces termino de rodillas, todo jadeante - Perotti Goloso",
	"No se dé que están hablando... Yo digo que sí a todo - Perotti Confundido",
	"No solo el Age está bugueado, el caster también está para la cagada - Perotti Definitive Edition",
	"¡Mamá! El Eish me trolea - F. erotti",
	"Tengo que actualizar el desactualizador para desactualizar - Perotti Redundante",
	"¡Esto es Socotra amigo! Acá se juega al eish, no a las casitas - Perotti Exigente",
	"No podés leer todo el chat, me pasa a mí en este canal que es una miseria - Perotti Malagradecido",
	"Vamos a ver tan rápido este Arena, que no se va a sentir - Perotti Experimentado",
	"Por prestar un buen servicio a la gente de la comunidad, ahora me quedo afuera - F. erotti",
	"El más grande de la noche lo tiene JP - Perotti Goloso",
	"¡Este chileno traidor! ¿Cómo se llama? ¿César? - Perotti Mala gente",
	"Me voy a ver a TheViper para desintoxicarme los ojos - Perotti Exigente",
	"Al pedo, como oreja de avión - Perotti Confundido",
	"Mejor no digo lo que iba a decir... Estos culiados después hacen una cita y me malinterpretan - Perotti Experimentado",
	"¡Oh, sí! Dame otro, dame otro - Perotti Goloso",
	"Mañana me pongo un vestido rosa y les casteo - Perotti Delirante",
	"Les voy a enviar una foto por discord, bien peludo y con escote - Perotti Conquistador",
	"Estoy muy chino, y no porque haya consumido nada - Perotti Confundido",
	"¡Igual hay casters que juegan bien eh! Por ejemplo, el Mastermind ese - Perotti Delirante",
	"Le faltó sabor, le falta sal al Capture Age - Perotti Di Cesare",
	"Ahora entiendo porque el capture Age es gratis - Perotti Malagradecido",
	"Yo soy de los veteranos, vengo jugando desde que se llamaban Invasores de Pasto - Perotti HD",
	"No tengo horario. A veces me paso 15 horas afuera, a veces voy 3 horas y vuelvo... a veces ni voy - Perotti Khemer",
	"Es el fast castle más fallido que vi en toda mi vida. Ni siquiera sé si fue fallido, parece que no llegó ni a proyecto ese Fast Castle - Perotti Exigente",
	"No me alcanzan los ojos para ver tanta cochinada - Perotti Exigente",
	"Todo chorreado, no importa, no importa - Perotti Goloso",
	"Soy la yerba del mate que chupas todas las mañanas - Perotti Delirante",
	"Estos son los mejores minutos que he perdido en mi vida - Perotti Sarcástico",
	"Por favor póngase cómodo, relájese y no piense mas en nada - Rastafarotti",
	"El pelado tiene el pecho peludo - Perotti Poeta Contemporáneo",
	"Con esta me retiro, a menos que sea muy corta - Perotti Goloso",
	"Olvida mi nombre, mi cara, mi castillo y pega la vuelta - Perotti Pimpinela",
	"¡Me están cagando a billetazos! ¿Qué pasó? ¿Cobraron el aguinaldo en febrero? - Perotti Agradecido",
	"Dirán que tengo hormigas en la cola... Ando inquieto, vengo y voy - Perotti Inquieto",
	"No quiero ser pesimista con el belga... pero lo están haciendo velga - Perotti Exigente",
	"Capoch tiene la base cómo su cabeza, toda pelada - Perotti Exigente",
	"Este tiene más protocolo que el Covid - Perotti Exigente",
	"Estoy pesimista, negativo... La gente se va ir a la mierda - Perotti Malagradecido",
	"¿Me robas? Yo te robo. Parece la Argentina esto - Perotti Traidor",
	"A Hera le debe estar temblando el bigote - Perotti Preocupado",
	"No le falta mucho, pero le falta más de lo que le faltaba antes... Se llama gasto público - Perotti Erudito",
	"Como oro no tiene, con el trash se entretiene - Perotti Erudito",
	"Me falta un Moderador de España y tengo a toda Latinoamérica - Perotti sin Fronteras",
	"Vende las cervezas más caras que la mierda. No sé con qué las hace, con oro creo - Perotti Malagradecido",
	"¿Aló?, ¿Sí?, Hablo con mi trabajo?, ¡Si!, ¡Bueno, GG! - Perotti Sarcástico",
	"Ya estoy para la cagada amigos y me queda otra serie... No sé cómo voy a hacer - Perotti Ebrio",
	"Siempre caballería nunca incaballería - Perotti Balvin",
	"¡Qué lindo los dos al mismo tiempo! Qué lindo, me ahorran la tildada - Perotti Agradecido",
	"¡Róbate ese chancho! ¡Hacelo por el bien de la comunidad! - Perotti Exigente",
	"La aldeana me deja la salchicha congelada arriba del fregadero - Perotti Goloso",
	"¡Se me deprimió el palito... Párate la conch4 de la lora! - F. erotti",
	"Perdí la virginidad nasal - F. erotti",
	"No es hate... Ustedes saben que es un jugador que yo admiro mucho, pero no deja de ser un pendejo pelotudo - Perotti Exigente",
	"El mod para espectear se llama Capture Age, y no te lo recomiendo amigo - Perotti Malagradecido",
	"Lierey se va pegando la vuelta, hace un rancho carancho!, Necesita otro bote brulote - Perotti Rapero",
	"Wuan, chu, trí - Perotti Bilingüe",
	"Estoy constipado cerebralmente - F. erotti",
	"La comida de caster es similar a comida de estudiante, pero sin fideos - Perotti Goloso",
	"No va a pasar nada, a menos que pase algo - Perotti Redundante",
	"Me voy a clavar una buena banana. Mira Patito, esta viene de donde vos sos - Perotti Goloso",
	"Tomando Coca? No seas rancio culiado - Perotti Exigente",
	"Sufrieron una erección las unidades militares de Viper - Perotti Mirando",
	"Gracias Blackdeath1970 por el cagazo que me hiciste pegar, y por el tremendo slingazo - Perotti Agradecido",
	"Es como un petardo al caballo - Perotti Imaginativo",
	"¡A ver, a ver, a ver, abajo del TC... Aaaaaay, sí! Dámela toda - Perotti Goloso",
	"Miren, así suena el ganso cuando lo tocas - Perotti Inimputable",
	"¡OHHH! Qué manera de chupetear la bombilla - Perotti con mate",
	"¡Waaaah! ¡Amigo estás loco! ¡Estás totalmente loco! 70 dólares! ¡Vos querés que yo renuncie a mi trabajo! Tremendo Cesarcete - Perotti Agradecido",
	"¡Gracias Enrique González! 10 dólares! Me emociono todo, me mojo todo, me asusto todo - Perotti Agradecido",
	"He visto ideas malas y después he visto esto - Perotti Exigente",
	"¿Te hicieron la gran Mundo AoE, Juan Esteban? - Perotti Remembers",
	"Sé lo que es romperse el ojete - Perotti Ex Aldeano Khemer",
	"Esos arqueros tiran flecha con la punta mocha - Perotti Herrero",
	"Capoch paso de ronda sin despeinarse jajajaja - Perotti Chistosito",
	"La tiene toda parada por acá, Dark - Perotti Observador",
	"¡Perdió la guerra por pete, Slam perdió por pete! - Perotti Hater",
	"Chúpale a mi camello las curvas - Perotti Arabiesco",
	"¿Vodka con Speed? Bueno, te la acepto solo por la bebida energizante - Perotti Cáster de la Red Bull",
	"Que Dios me libre de mí mismo - Perotti Caducado",
	"¡Se terminó el humo amigos! - Perotti Recargando Humo",
	"TheViper duró menos que un pedo en el aire - Perotti Físico",
	"Voy a respirar cuando me falte el aire - Perotti Apnea",
	"Ahí me auto... ehh... me auto... no sé qué auto - Perotti Auto",
	"¡Gracias Endo! Un mal necesario usted, aquí y en todo el Flauta - Perotti Resentido",
	"Cuando sea grande y rico, voy a hacer un Bar del Age - Perotti Ricachón",
	"¡Vamos Endo viejo, lindo y peludo! - Perotti Endonamorado",
	"Voy a aprovechar ese sonido para limpiarme la nariz - Perotti Mocoso",
	"Se viene algo, pero no voy a abrir la boca porque me sale humo - Perotti Máquina de Humo",
	"Voy a dejar de divertirme con la aldeanita, ahora me voy a divertir con ustedes - Perotti Bisexual",
	"Empecé a castear después de ver a mis colegas hacerlo, y vi que podía hacerlo mejor - Humildad Perotti",
	"¡No! me tiró el tornado, la kk esta - Perotti Antideportivo",
	"Si Nicov pierde esta serie, todos ponen dislike - Perotti Mufa",
	"Es una civ Jemérica, no genérica - Perotti Jemer",
	"Encima es un garca, me tocan garcas en todo lado - Perotti Indignado",
	"Es monje la vieja, Los convence, y me imagino como los convence - Perotti Mal Pensado",
	"¡Vamos a morir peleando! - Perotti Gladiador",
	"Le están deformando el asterisco - Perotti Segunda Opinión",
	"La ignorancia, con mucho dinero y mucho poder, es muy peligrosa - Perotti Sociólogo",
	"Improvisando, como un blues en La Menor - Perotti Mississippi",
	"Siempre que veas un ruso jugando al Age, lo vas a ver peleando contra un oso en algún momento - Camarada Perotti",
	"Por eso no hay que estudiar, para que gastar plata en libros - Perotti Oscurantista",
	"Voy a hacer mi propio Age of Empires, con juegos de azar y unidaderzuelas - Perotti Empresario",
	"Esto no es el Caster Infiltrado, esto es Casteando Boludos - Perotti Amigo",
	"No sé, no tengo ni idea, no lo vi nunca al mapa - Perotti Erudito del Age",
	"Esto es para reírse de los demás, no para reírse de uno mismo - Perotti Infiltrado",
	"Ya se viene Dogao. Ernesto, cuidado con esto! - Perotti Poeta Involuntario",
	"¡Ahí está el mono, ahí está el culpable de todo! - Perotti con Resaca",
	"Debería haber un mod para que las reliquias sean monjas, así los monjes las agarran y ¡Pumba! - Perotti Indecente",
	"A Villese le está por fallar el sistema hidráulico - Perotti Mecánico",
	"El Camello Arquero es una de las mejores unidades del juego, lo dijo el robot – Perottillese",
	"Se me calentó el pico, gorda - Perotti Ferneteado",
	"¡Uy! ¡Se chocaron las aldeanas, malísimo! Se tosquean... nah, muy bueno - Perotti Indeciso",
	"Es un test de estrés, tenemos que estresar a la tostadora - Perotti Ingeniero en Sistemas",
	"Soy como el Freddy Krueger del Eish. Me meto en tus sueños y te los casteo - Perotti en tus Sueños",
	"Ven Selva Negra y se meten todos los petes - Perotti Hater Again",
	"El trote que me pegué hasta la heladera fue impresionante - Perotti Gordo",
	"Cuatro hamburguesas se comió el HDPT - Perotti Hambriento",
	"Yo estoy comiendo Age. Me alimento de la química, del +3 - Perotti Nutricionista del Age",
	"Ese Castillo te va a durar lo que un pedo en el aire - Perotti Metafórico",
	"Llegaste tarde a la repartición de posibilidades de penetración - Perotti Rapero Goloso",
	"¿Quieres preguntar en el chat en vivo? Haz un canal y ponte a castear - Perotti Odioso",
	"El Capture Age está más mal optimizado que nuestra relación - Perotti Duerme Afuera",
	"A la cebolla no llegamos ni en pedo - Perotti en Fin de Mes",
	"Se están matando los más mancos del equipo - Perotti Flauta",
	"Soy una especie de Apu del Age - Perotti en Horas Extras",
	"Me llegaron los slingazos, era más fácil de lo que pensaba - Perotti Anti Abraxas",
	"Son cuadritos moviéndose por un plano - Perotti.exe",
	"Me chorrea el bife - Perotti Degustando",
	"Me acabas de hacer una caricia al alma - Perotti Cariñosito",
	"Como me gusta cuando entran los miembros - Perotti Complacido",
	"Valoro que valoren el valor del casteo - Perotti Sobrevalorado",
	"Vamos a darle piripipí, piripipí - Perotti Pipí",
	"La única verdad es la realidad - Perotti Realismo Contemporáneo",
	"La lógica nunca fue uno de los fines del Age - Perotti Lógico",
	"Seguramente me tendré que mamar la propaganda - Perotti Mamador",
	"No me alcanzan las manos y la boca para saludar a todos - Perotti Poli amor",
	"Se llenó de miembros, estoy re contento - Perotti Gustoso",
	"Quieren venir y agarrar la Flauta y soplarla - Perotti Líder del Flauta",
	"Primero me llenan la cara de Miembros, luego me donan y me voy para Miami - Perotti Vividor",
	"La esnipeación del escautismo - Perotti RAE",
	"La Aldeanita me distrae un montón, pero ya se fue a la mierda - Perotti Esposo",
	"A JorDan le salió el alemán de adentro - Führer Perotti",
	"Si la Aldeanita me manda a donde mi vieja es lo mismo - Perotti Freud",
	"No soy religioso, pero gracias Virgencita querida - Perotti con la Fe Desarrollada",
	"¡Qué bien que hicieron en regalarle el Age of Empires a Lierey! Mi vieja no puede decir lo mismo - Perotti Cáster",
	"Lancero que ¡Pumba! pero aldeano que ¡Tuki! - Perotti Onomatopéyico",
	"A veces me pregunto, ¿qué hago casteando? Mejor me voy al campito. Después me donan y se me pasa - Perotti Money",
	"Dale tranquila gorda, podes pasearte en bolas si quieres - Perotti Esposo Irónico",
	"Yo me busco la ropa. Lo que pasa es que es práctico que te pasen las cosas - Perotti Esposo Perezoso",
	"Quizás tu necesites viagra, sin ofender - Perotti Ofendido",
	"El lideraje indiscutible – Perottiaje",
	"¡Pumba!, ¡Puso!, ¡Lleve!, ¡Coma pan! - Juancete Expresivo",
	"¿Se puede hacer desde la compu?, ¿Por qué nadie me lo dijo antes? - Perotti de Madera",
	"Puedo haber sido peor, pero terminó mucho peor de lo que pudo haber sido - Juancete Inmortal",
	"¡Hace dos horas que estoy diciendo lo mismo, pero que denso! - Perotti Denso",
	"Yo los pongo manualmente - Perotti Manuela",
	"Endo rima con horrEndo - Perotti Amigo",
	"Catapulta que catapultea a la catapulta catapulteada - Perotti Caster Pro",
	"¡Pero la Gran Flauta que lo tiro de las patas! - Perotti Enfadado",
	"Sí, este año sale probablemente en diciembre sale Commandos - Perotti 9 de enero de 2022",
	"Decime que quieres y te lo muestro - Perotti Only Fans",
	"No te recomiendo dormir conmigo, tengo gases - Perotti Flatulencias",
	"Nos cagabamos de risa... No, la verdad nos puteab@mos - Perotti Tóxico",
	"Hay más probabilidades de que te vayas del Flauta que yo del Age - Perotti Amigo Sincero",
	"¡Cómo me gusto, que tipo pelotudo que soy! - Perotti Narcisista",
	"Alguno se estaba fumando un pucho, le explotó una piedra en la cara y descubrió la pólvora - Perotti History Channel",
	"Me quedé con el Pumba en la boca - Perotti Pumba",
	"Esta partida se la lleva Lyx por sofocación económica - Perotti Milei",
	"Che me agarró el frío, ¿qué me pasa?, Estoy menopáusica - Perotti Cuarentón",
	"Hace falta una bebida espirituosa - Perotti A.A",
	"Cuando llego, la aldeana me resuelve todos los problemas alimenticios. Estoy bien atendido, sabes - Perotti Atendido",
	"Llegamos a 5500 Subs hoy y me pongo un sombrero rosita - Perotti Rosita",
	"¿Para qué quieres la llave Diego?, como si la fueras a utilizar sabiamente - Perotti Sabio",
	"Yo estaba jugando para hinchar las bolas, nada más - Perotti hichabolas",
	"Demo que ¡Pumba!, Brulote que ¡Pfff! - Perotti Sinfónico",
	"¡Oh no! ¡Capoch le va hacer el amor - Perotti Nopor",
	"El único fin de estudiar es terminar los estudios - Perotti Consejero Escolar",
	"Los chanchitos ovejísticos - Perotti NatGeo",
	"No tengo mate para escupirte, pero te bendigo verbalmente - Perotti Wololo",
	"Como se deben querer tijeretear las pelotas los que dijeron que se iba acabar con el Age 2 - Perotti Resentido",
	"Que buen volvido - Perotti Caster Pro",
	"Esos piqueros se desMayan contra las Catafractas... Se desAztecan en este caso - Invente Perotti, Invente",
	"Me caigo de culo, me muero, me levantó y me vuelvo a morir - Perotti Ciclo de Vida",
	"Se saborean... La potencia que tienen... Un caldo, puedes hacer sopa con el olor ese - Perotti Master Chef",
	"Me lo anotas y mañana te pagó - Perotti Moroso",
	"Solo me queda chuparme el dedo gordo - Perotti Resignado",
	"Las cosas son lo que nosotros inventamos - Perotti Filosofal",
	"Te explota por el trasero, cómo peligroso - Perotti Experimental",
	"Soy mala gente, mala persona... No le digan a nadie - Perotti Mala Gente",
	"Esta citante y excitante, como siempre - Perotti Excitado",
	"Tiene más ejército que unidades militares - Perotti Confundido",
	"Puedo pensar cosas que nunca digo - Perotti Filósofo",
	"Vengo contando los Miembros - Perotti Promiscuo",
	"Hola chino querido, váyase a la verga. Igual no entiende nada - Perotti Argentino",
	"Quien no llora, no mama - Perotti Citador",
	"Es exclusivo de la CaduCup, no lo robamos de un torneo menos popular - Perotti Lamer",
	"¡Ohhh Aldeana!... que me babeas el hombro y me roncas al oído todas las noches - Perotti Romántico",
	"Nunca veo las ovejas, cuando juego tampoco - Perotti Noob",
	"El Flauta es un Pro intermitente - Perotti Flautesco",
	"No deja de profesar su amor por la banana Ecuatoriana - Perotti Celoso",
	"Los hacemos llorar y cuando lloren, los baneamos - Perotti Dictador",
	"No le pude inventar un sufijo a una palabra - Perotti RAE",
	"Esperemos que no nos claven - Perotti Pretensioso",
	"La Flauta, de por sí, es un Meme - Perotti Líder Flauta",
	"Si esa es su inquietud, yo se la evacúo ' Perotti Laxante",
	"Te voy a enviar una tanga a domicilio amigo Ramoc",
	"Te la mereces por tanto apoyo - Perotti Agradecido",
	"Que te lo va a tomar a ti, que vienes de Parcerolandia - Perotti Parcero",
	"¿La Vaca? La Vaca está ahí afuera tomando sol - Perotti Ganadero",
	"En realidad, está bien lo que dije, lo que pasa es que suena feo - Perotti Sin Filtro",
	"Pero por supuesto mi amor... Mi amor le digo, a vos te digo amiga y a los muchachos mi amor - Perotti Romántico",
	"No hay nada peor que no escucharse - Perotti Sabio Sonidista",
	"EnriqueRider podemos decir que tienes la más grande del canal...refiriéndome a las donaciones – Perotti Destronador de JP's.",
	"Leelo exijo mi derecho de miembro - Aldeana inimputable",
	"Los reto a que preparen un mejor Fernet que el de mi suegro y no es por ser chupa media - Perotti Chupa Media",
	"Este suegro se tienen que conseguir ustedes, el que te trae el café batido mientras jugas al Age - Perotti Yerno",
	"Pero aldeana, cálmese señora - Perotti Homeless",
	"Puedo estar un poco ebrio, pero ustedes son raros eh - Perotti Ebrio y Sincero",
	"Que juego de poronga - Perotti Capochista",
	"Ayyy se me asustó el Pelón - Perotti Tímido",
	"Gana rápido que tenemos que ver el partido - Perotti Fubolito",
	"¿Ah Ma! que cosa, la avestruze se me revela - Tano Perotti",
	"No me lo obliguen a trabajar que se va herniar - Perotti Sindicato",
	"Mi abuela hablaba mejor que yo, tendría que ser caster - Perotti Familiar",
	"Tengo unas ganas de raidear a alguien - Perotti de Armas",
	"Me voy a tronar el Ganso - Perotti 15 años",
	"JorelSan me rompiste el stream amigo, 20 regalaste estás loco...y ahora como paro la musiquita - Perotti Desconcertado",
	"¿A dónde era que llegaron? a Israel? Ponele.... Tengo menos Monasterio que un Persa - Perotti con Herejía",
	"No todo lo que caduca al Dravídico es culpa del Dravídico – Perotti",
	"Me gusta que te guste, lo que me gusta - Perotti Agradecido",
	"Qué lindo cuando la gente te apoya con su miembro - Perotti Agradecido",
	"Aguántate las ganas de mear amigo - Perotti Incontinencia",
	"Vino la aldeana y me desconcertó con tanta belleza - Perotti Ebrio de Amor",
	"Me estaba sacando un marciano - Perotti Mocoso",
	"Este coso tiene daño en penetración - Perotti Explícito",
	"No soy prostituto hijo, me puedo pelar por amor al arte, no por dinero - Perotti Only Fans",
	"Estoy casteando tanto que no puedo beber - Perotti Alcohólicos Anónimos",
	"Pregunté así en voz alta, sin preguntarle a nadie - Perotti Curioso",
	"No les voy a vender humo porque apenas puedo respirar - Perotti Ahumado",
	"Me voy a tomar un té de muñequito - Perotti GG",
	"Me estoy muriendo - RIPerotti 06-05-2022",
	"Tengo la muñeca derecha tan bien entrenada que la puedo tocar sin problemas - Perotti Pajero",
	"Vino la aldeana y me dejó todo abierto y frío - Perotti Menopaúsico",
	"Pareces un Mapache invertido, cómo te vas a dejar los lentes - Perotti Romántico",
	"Me estaba muriendo de hambre, menos mal llegaste - Perotti Atenido",
	"Si no wallea, se la come - Perotti Sobre aviso",
	"Esta sopa tiene el +4 de calor - Perotti en Llamas",
	"Voy a quedar con el cul0 cuadrado - Perotti Minecraft",
	"Tengo ganas de levantar las patas y caminar un poco - Perotti Atleta",
	"Es mi opinión y se me antoja darla - Perotti Antojado",
	"Hay algo en Nicov que está roto y no es su corazón - Perotti Poeta Contemporáneo",
	"Estoy viendo cosas que aún no suceden - Perotti Visionario",
	"Yo elijo el franco toda la vida, no soy de las nuevas civis - Perotti Conservador",
	"Está Wall tan grande cómo innecesaria - Perotti Crítico",
	"Otro que se va para Europa para sliguear y que el Caster viva cómo si estuviera allá - Perotti Acomodado",
	"Del amigo Zanette le dicen Salite de acá - Perotti Rimas Forzadas",
	"¿Se puede ir a mear? ...que si se puede lamear en el torneo Nacho - Perotti Malinterpretado",
	"¡Ariete de Asedio Mongol, si saliera es el nuevo DLC dirían ‘ay, está roto, está roto’! - Perotti con Instrucción Militar",
	"No sé cómo se Castea con el Capture Age - Perotti Modesto",
	"No me digas que me la clave - Perotti Autocomplaciente",
	"El cordobés es un porteño del interior, no hay forma... El tipo siempre te va a dar cátedra de hasta las cosas que no sabe, te chamuya - Perotti Cordobés",
	"Vos no viniste en barco, tu abuelo es un comechingón hermoso, bonificación de ataque contra Infantería tiene, un Hondero es tu abuelo – Perotti Historiador",
	"Cuándo usted done más de un dólar, traemos el Age lV - Perotti Negociador",
	"Ya la voy a agarrar a esa Copa Libertadores, y le voy a pegar una casteada bárbara - Perotti Atrasado",
	"Se vienen los Camellos Arqueros... los Elefantes Arqueros a Camello Montado con Arco - Perotti DLC",
	"Déjame así, no me corrija que no aprendo, digo para que no pierda tiempo viste que uno es medio burro - Juancete Caducado",
	"Esa Wall me parece tan rancia como eficaz - Perotti Dicotómico",
	"Hay un par de niños rata por acá, no les presten atención - Perotti Papá",
	"Dame Helado, exploto hoy - Perotti Colon Irritado",
	"El Pato tira información, ustedes Boludean - Perotti Favoritismo",
	"El dinero no me hace feliz, me hace falta - Perotti Financiero",
	"Escucho Coldplay y me dan ganas de buscar la 22 y pegarme un corchazo - Perotti Musical",
	"Mañana me tomo el día, hoy el shampoo - Perotti Organizador",
	"Mono monkey ctm estoy…mal - Perotti Agradecido",
	"Manko dame las opciones o me llevo una moneda - Perotti Jugado",
	"Necesito otra CaduCup, pero sin gente que lloré - Perotti Sponsor",
	"Es como que todo el tiempo te estas garchando a la vela - Perotti Fantasioso",
	"Ahora suscribite por pelotudo - Perotti Simpático",
	"Te voy a contar una anécdota, pero en un rato porque se me hace muy larga - Perotti Conversador",
	"No puedo dejar de mirar los miembros - Perotti Goloso",
	"¡Ah mira q lindo esta aa.… está hecho poronga, pero está bueno¡ - Perotti picarón"
       );
   $random = array_rand($respuestas);
   echo $respuestas[$random];
?>